I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script2.rpy", line 173, in script
    with Shake((0, 0, 0, 0), 3.0, dist=30)
  File "game/script2.rpy", line 173, in <module>
    with Shake((0, 0, 0, 0), 3.0, dist=30)
NameError: name 'Shake' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script2.rpy", line 173, in script
    with Shake((0, 0, 0, 0), 3.0, dist=30)
  File "/Volumes/renpy-8.1.3-sdk/renpy-8.1.3-sdk/renpy/ast.py", line 1671, in execute
    trans = renpy.python.py_eval(self.expr)
  File "/Volumes/renpy-8.1.3-sdk/renpy-8.1.3-sdk/renpy/python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Volumes/renpy-8.1.3-sdk/renpy-8.1.3-sdk/renpy/python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script2.rpy", line 173, in <module>
    with Shake((0, 0, 0, 0), 3.0, dist=30)
NameError: name 'Shake' is not defined

macOS-14.2.1-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
Transition of Instances 1.0
Thu Dec 28 11:56:20 2023
